### ISSUE TITLE
Dockerfiles creates problematic Volumes

### ISSUE THREAD

**Issue by waja** [bodsch/docker-icingaweb2#32]
You are defining volumes in https://github.com/bodsch/docker-icingaweb2/blob/master/Dockerfile#L193.

When restarting the container there is thrown the following error:

```
ERROR: for icingaweb2  Cannot create container for service icingaweb2: invalid volume specification: '4b1991574d581e90140d1388ed93b143e7ba4afd87816445455ac3cbfa599e0e:]:rw': invalid mount config for type "volume": invalid mount path: ']' mount path must be absolute

ERROR: for icingaweb2  Cannot create container for service icingaweb2: invalid volume specification: '4b1991574d581e90140d1388ed93b143e7ba4afd87816445455ac3cbfa599e0e:]:rw': invalid mount config for type "volume": invalid mount path: ']' mount path must be absolute
```
Looking into `docker inspect` reveals (spot for 'Destination'!) : 

```yaml
        "Mounts": [
            {
                "Type": "volume",
                "Name": "2a81ad51713b3637a0ba145f23eead82e3f7382594213a11c1c6da2610e8f894",
                "Source": "/var/lib/docker/volumes/2a81ad51713b3637a0ba145f23eead82e3f7382594213a11c1c6da2610e8f894/_data",
                "Destination": "/etc/icingaweb2",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "d05f4579c0afd562e674fe37b00a2f28e7b3b546ed5c239797eadae5737aa850",
                "Source": "/var/lib/docker/volumes/d05f4579c0afd562e674fe37b00a2f28e7b3b546ed5c239797eadae5737aa850/_data",
                "Destination": "/init/custom.d",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "b853dd500e6519a775358823b3570efb6df07db5f1467de7d5521ac84dae6dce",
                "Source": "/var/lib/docker/volumes/b853dd500e6519a775358823b3570efb6df07db5f1467de7d5521ac84dae6dce/_data",
                "Destination": "/usr/share/webapps/icingaweb2",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "010feab79fc569e0fe5cb143895467247351858eb2c901e79c49852b05435181",
                "Source": "/var/lib/docker/volumes/010feab79fc569e0fe5cb143895467247351858eb2c901e79c49852b05435181/_data",
                "Destination": "[",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "4b1991574d581e90140d1388ed93b143e7ba4afd87816445455ac3cbfa599e0e",
                "Source": "/var/lib/docker/volumes/4b1991574d581e90140d1388ed93b143e7ba4afd87816445455ac3cbfa599e0e/_data",
                "Destination": "]",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```
The last two volumes seems problematic.

Maybe you need to remove the Whitepsaces maybe? See https://docs.docker.com/engine/reference/builder/#volume
